codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "95...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

ignore:
  - "**/*.freezed.dart"
  - "**/*.g.dart"
  - "packages/flusmic/example"
  - "packages/flusmic_ui/example"
  - "packages/flusmic_ui/lib/src/models"